//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudbassCRUDII.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CBDBEntities : DbContext
    {
        public CBDBEntities()
            : base("name=CBDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categ> Categs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Crew> Crews { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Has_Role> Has_Role { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<SchType> SchTypes { get; set; }
    }
}
