//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudbassCRUDII.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CloudbassDBMSEntities : DbContext
    {
        public CloudbassDBMSEntities()
            : base("name=CloudbassDBMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingCrew> BookingCrews { get; set; }
        public virtual DbSet<BookingEquipment> BookingEquipments { get; set; }
        public virtual DbSet<BookingFleet> BookingFleets { get; set; }
        public virtual DbSet<BookingKit> BookingKits { get; set; }
        public virtual DbSet<Categ> Categs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipType> EquipTypes { get; set; }
        public virtual DbSet<Fleet> Fleets { get; set; }
        public virtual DbSet<FleetType> FleetTypes { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobStatu> JobStatus { get; set; }
        public virtual DbSet<Kit> Kits { get; set; }
        public virtual DbSet<KitType> KitTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScheduleStatu> ScheduleStatus { get; set; }
        public virtual DbSet<SchType> SchTypes { get; set; }
        public virtual DbSet<Has_Role> Has_Role { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    }
}
