//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudbassCRUDII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew
    {
        public string jobId { get; set; }
        public int has_RoleId { get; set; }
        public Nullable<decimal> totalDays { get; set; }
    
        public virtual Has_Role Has_Role { get; set; }
        public virtual Job Job { get; set; }
    }
}
