//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudbassCRUDII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public string Id { get; set; }
        public string text { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string NameConcatenatLocation
        {
            get { return text + " - " + Location; }
        }

        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> TXDate { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string Coordinator { get; set; }
        public string CommercialLead { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> statusId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual JobStatu JobStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
